/-
Copyright (c) 2026 Johnny Shields. All rights reserved.
Released under the MIT license as described in the file LICENSE.txt.
Authors: Johnny Shields
-/
import Mathlib.Analysis.Complex.Basic
import Mathlib.Analysis.Normed.Module.FiniteDimension
import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.Algebra.Polynomial.Degree.Support
import Mathlib.Algebra.Polynomial.FieldDivision
import Mathlib.Topology.Maps.Proper.Basic

/-!
# Upper semicontinuity of the degree of a greatest common divisor

For a family of pairs of polynomials of constant degrees whose coefficients vary continuously,
the parameters at which the pair carries a common factor of degree at least `d` form a **closed**
set: `deg gcd` cannot jump down in the limit, only up.

The route is the classical Bézout comparison.  Writing `n = deg P` and `m = deg H`,

> `P` and `H` have a common factor of degree `≥ d`
> `⟺ AP + BH = 0` for some `(A,B) ≠ 0` with `deg A ≤ m - d` and `deg B ≤ n - d`,

which turns the condition into the existence of a nonzero vector in a *fixed* finite-dimensional
space, the coefficients of `AP + BH` being polynomial in those of `A`, `B`, `P` and `H`.
Normalizing `(A,B)` to the unit sphere makes the fiber compact, so the parameter set is the image
of a closed set under a projection along a compact factor, hence closed.

## Main definitions

* `Shields.HasCommonFactor`: `P` and `H` admit a common divisor of degree at least `d`.
* `Shields.toPoly`: the polynomial with a prescribed coefficient vector, `∑_{i<a} uᵢXⁱ`.
* `Shields.syzygyLocus`: the pairs `(λ, u)` with `u` a unit coefficient vector whose blocks
  annihilate the pair at `λ`.

## Main results

* `Shields.hasCommonFactor_iff`: the Bézout comparison.
* `Shields.setOf_hasCommonFactor_eq_image`: the comparison as a set identity — the parameter set
  is the projection of the syzygy locus.
* `Shields.isClosed_syzygyLocus`: the locus is closed, the coefficients being convolutions.
* `Shields.isClosed_hasCommonFactor`: **upper semicontinuity**, the closedness statement above.
* `Shields.isOpen_not_hasCommonFactor`: the complementary open set.

## Implementation notes

`HasCommonFactor P H d` is spelled as the existence of a common divisor of degree at least `d`
rather than as `d ≤ (gcd P H).natDegree`, which keeps the statement free of a `DecidableEq`
instance and of any gcd normalization.  The comparison needs no gcd API at all — only that `K[X]`
is a principal ideal ring, so that the ideal generated by `P` and `H` has a generator
`g = uP + vH`, whence `uP₁ + vH₁ = 1` and the divisibility `H₁ ∣ A`.

`toPoly` is an unbundled section of the coefficient map, deliberately not `degreeLTEquiv.symm`:
the argument multiplies it by a varying polynomial and reads off coefficients, and a bare
function into `K[X]` avoids carrying the `degreeLT` subtype through every continuity estimate.

The algebra is over an arbitrary field; only the semicontinuity is stated over `ℂ`, where it uses
that spheres in a finite-dimensional space are compact.

## Tags

polynomial, gcd, resultant, semicontinuity, Bézout, common factor
-/

open Polynomial

namespace Shields

/-! ### Common factors and the Bézout comparison -/

variable {K : Type*} [Field K]

/-- `P` and `H` carry a common factor of degree at least `d`.  This is `d ≤ deg gcd(P,H)`
without naming a gcd, which keeps the statement free of a `DecidableEq` instance. -/
def HasCommonFactor (P H : K[X]) (d : ℕ) : Prop :=
  ∃ g : K[X], g ∣ P ∧ g ∣ H ∧ d ≤ g.natDegree

theorem HasCommonFactor.le_natDegree {P H : K[X]} {d : ℕ} (h : HasCommonFactor P H d)
    (hH : H ≠ 0) : d ≤ H.natDegree :=
  let ⟨_, _, hgH, hdg⟩ := h
  hdg.trans (Polynomial.natDegree_le_of_dvd hgH hH)

theorem hasCommonFactor_zero (P H : K[X]) : HasCommonFactor P H 0 :=
  ⟨1, one_dvd _, one_dvd _, Nat.zero_le _⟩

/-- Bézout in `K[X]`: a common divisor of `P` and `H` that is also a combination of them.  This
is the generator of the ideal they span, and it is all the gcd theory the comparison below
uses. -/
theorem exists_bezout (P H : K[X]) : ∃ g u v : K[X], g ∣ P ∧ g ∣ H ∧ u * P + v * H = g := by
  letI : DecidableEq K := Classical.decEq K
  obtain ⟨u, v, huv⟩ := IsBezout.gcd_eq_sum P H
  exact ⟨IsBezout.gcd P H, u, v, IsBezout.gcd_dvd_left P H, IsBezout.gcd_dvd_right P H, huv⟩

/-- The degree of a nonzero polynomial splits over any factorization of it.  This is
`Polynomial.natDegree_mul` in the form a divisibility witness `P = g * Q` delivers, where the
two factors are nonzero for the same reason. -/
theorem natDegree_eq_add_of_eq_mul {P g Q : K[X]} (hP : P ≠ 0) (hPQ : P = g * Q) :
    P.natDegree = g.natDegree + Q.natDegree := by
  rw [hPQ, Polynomial.natDegree_mul (left_ne_zero_of_mul (hPQ ▸ hP))
    (right_ne_zero_of_mul (hPQ ▸ hP))]

/-- **The Bézout comparison.**  A common factor of degree at least `d` is the same thing as a
nonzero syzygy `AP + BH = 0` with `deg A ≤ deg H - d` and `deg B ≤ deg P - d`.  The forward
direction takes `(A,B) = (H/g, -P/g)`; the backward one divides by the generator of the ideal
spanned by `P` and `H` and reads `H₁ ∣ A` off the Bézout relation. -/
theorem hasCommonFactor_iff {P H : K[X]} (hP : P ≠ 0) (hH : H ≠ 0) {d : ℕ}
    (hd : d ≤ H.natDegree) :
    HasCommonFactor P H d ↔
      ∃ A B : K[X], (A ≠ 0 ∨ B ≠ 0) ∧ A.natDegree ≤ H.natDegree - d ∧
        B.natDegree ≤ P.natDegree - d ∧ A * P + B * H = 0 := by
  constructor
  · rintro ⟨g, ⟨P₁, hP₁⟩, ⟨H₁, hH₁⟩, hdg⟩
    have hH₁0 : H₁ ≠ 0 := right_ne_zero_of_mul (hH₁ ▸ hH)
    have hdegP := natDegree_eq_add_of_eq_mul hP hP₁
    have hdegH := natDegree_eq_add_of_eq_mul hH hH₁
    refine ⟨H₁, -P₁, Or.inl hH₁0, by omega, ?_, ?_⟩
    · rw [Polynomial.natDegree_neg]; omega
    · rw [hP₁, hH₁]; ring
  · rintro ⟨A, B, hAB, hA, _, hrel⟩
    have hA0 : A ≠ 0 := fun hA0 => hAB.elim (fun h => h hA0) fun h => h <| by
      rw [hA0, zero_mul, zero_add] at hrel
      exact (mul_eq_zero.mp hrel).resolve_right hH
    obtain ⟨g, u, v, ⟨P₁, hP₁⟩, ⟨H₁, hH₁⟩, huv⟩ := exists_bezout P H
    have hg : g ≠ 0 := left_ne_zero_of_mul (hP₁ ▸ hP)
    -- dividing a relation `sP + tH = gc` through by the common factor `g`
    have hdiv : ∀ s t c : K[X], s * P + t * H = g * c → s * P₁ + t * H₁ = c :=
      fun s t c hst => mul_left_cancel₀ hg <| by
        rw [show g * (s * P₁ + t * H₁) = s * (g * P₁) + t * (g * H₁) by ring, ← hP₁, ← hH₁, hst]
    have hone : u * P₁ + v * H₁ = 1 := hdiv u v 1 (by rw [huv, mul_one])
    have hcancel : A * P₁ + B * H₁ = 0 := hdiv A B 0 (by rw [hrel, mul_zero])
    have hdvd : H₁ ∣ A := ⟨v * A - u * B, by
      calc A = A * (u * P₁ + v * H₁) := by rw [hone, mul_one]
        _ = u * (A * P₁ + B * H₁) + H₁ * (v * A - u * B) := by ring
        _ = H₁ * (v * A - u * B) := by rw [hcancel, mul_zero, zero_add]⟩
    have hle : H₁.natDegree ≤ A.natDegree := Polynomial.natDegree_le_of_dvd hdvd hA0
    have hdegH := natDegree_eq_add_of_eq_mul hH hH₁
    exact ⟨g, ⟨P₁, hP₁⟩, ⟨H₁, hH₁⟩, by omega⟩

/-! ### Coefficient vectors -/

/-- The polynomial with prescribed coefficient vector, `∑_{i<a} uᵢXⁱ`. -/
noncomputable def toPoly {a : ℕ} (u : Fin a → K) : K[X] := ∑ i : Fin a, C (u i) * X ^ (i : ℕ)

theorem coeff_toPoly {a : ℕ} (u : Fin a → K) (j : ℕ) :
    (toPoly u).coeff j = if h : j < a then u ⟨j, h⟩ else 0 := by
  rw [toPoly, Polynomial.finsetSum_coeff]
  simp only [Polynomial.coeff_C_mul, Polynomial.coeff_X_pow, mul_ite, mul_one, mul_zero]
  by_cases h : j < a
  · rw [dif_pos h]
    rw [Finset.sum_eq_single (⟨j, h⟩ : Fin a)]
    · simp
    · intro c _ hc
      refine if_neg fun hj => hc ?_
      exact Fin.ext hj.symm
    · intro hmem
      exact absurd (Finset.mem_univ _) hmem
  · rw [dif_neg h]
    refine Finset.sum_eq_zero fun i _ => if_neg fun hji => h ?_
    rw [hji]; exact i.isLt

theorem toPoly_eq_zero_iff {a : ℕ} {u : Fin a → K} : toPoly u = 0 ↔ u = 0 := by
  refine ⟨fun h => funext fun i => ?_, fun h => by simp [toPoly, h]⟩
  have hc := coeff_toPoly u (i : ℕ)
  rw [h, Polynomial.coeff_zero, dif_pos i.isLt] at hc
  simpa using hc.symm

theorem natDegree_toPoly_le {a : ℕ} (u : Fin a → K) : (toPoly u).natDegree ≤ a - 1 := by
  rw [Polynomial.natDegree_le_iff_coeff_eq_zero]
  intro j hj
  rw [coeff_toPoly, dif_neg (by omega)]

theorem toPoly_coeff {a : ℕ} (A : K[X]) (h : A.natDegree < a) :
    toPoly (fun i : Fin a => A.coeff (i : ℕ)) = A := by
  ext j
  rw [coeff_toPoly]
  by_cases hj : j < a
  · rw [dif_pos hj]
  · rw [dif_neg hj]
    exact (Polynomial.coeff_eq_zero_of_natDegree_lt (by omega)).symm

theorem toPoly_smul {a : ℕ} (c : K) (u : Fin a → K) : toPoly (c • u) = C c * toPoly u := by
  simp only [toPoly, Finset.mul_sum, Pi.smul_apply, smul_eq_mul, map_mul]
  exact Finset.sum_congr rfl fun i _ => by ring

/-- Rescaling a pair of coefficient vectors rescales the syzygy their blocks define. -/
theorem toPoly_smul_mul_add {a b : ℕ} (t : K) (w : (Fin a → K) × (Fin b → K)) (P H : K[X]) :
    toPoly (t • w).1 * P + toPoly (t • w).2 * H
      = C t * (toPoly w.1 * P + toPoly w.2 * H) := by
  rw [Prod.smul_fst, Prod.smul_snd, toPoly_smul, toPoly_smul]; ring

/-- The coefficients of `(∑_{j<a} uⱼXʲ)P` are the convolution, which is what makes them
continuous in `(u, P)`. -/
theorem coeff_toPoly_mul {a : ℕ} (u : Fin a → K) (P : K[X]) (i : ℕ) :
    (toPoly u * P).coeff i = ∑ j : Fin a, u j * (if (j : ℕ) ≤ i then P.coeff (i - j) else 0) := by
  rw [toPoly, Finset.sum_mul, Polynomial.finsetSum_coeff]
  refine Finset.sum_congr rfl fun j _ => ?_
  have hcomm : C (u j) * X ^ (j : ℕ) * P = C (u j) * (P * X ^ (j : ℕ)) := by ring
  rw [hcomm, Polynomial.coeff_C_mul, Polynomial.coeff_mul_X_pow']

/-! ### Semicontinuity -/

section Topology

variable {Λ : Type*} [TopologicalSpace Λ]

/-- The **normalized syzygy locus** of a family of polynomial pairs: those `(\lambda, u)` with `u`
a coefficient vector of unit norm whose two blocks `A = \sum u_i X^i` and `B` annihilate the pair,
`AP(\lambda) + BH(\lambda) = 0`.

The whole point of normalizing to the sphere is that the fiber over `\lambda` is then compact, so
the projection to the parameter is a closed map. -/
def syzygyLocus (P H : Λ → ℂ[X]) (a b : ℕ) :
    Set (Λ × Metric.sphere (0 : (Fin a → ℂ) × (Fin b → ℂ)) 1) :=
  {q | toPoly (q.2 : (Fin a → ℂ) × (Fin b → ℂ)).1 * P q.1
        + toPoly (q.2 : (Fin a → ℂ) × (Fin b → ℂ)).2 * H q.1 = 0}

/-- **The syzygy locus is closed.**  A polynomial vanishes exactly when all its coefficients do,
and each coefficient of `AP + BH` is the convolution `\sum_j u_j P_{i-j}`, which is continuous in
the parameter and in the coefficient vector jointly. -/
theorem isClosed_syzygyLocus {P H : Λ → ℂ[X]} {a b : ℕ}
    (hPc : ∀ i, Continuous fun l => (P l).coeff i)
    (hHc : ∀ i, Continuous fun l => (H l).coeff i) :
    IsClosed (syzygyLocus P H a b) := by
  set E := (Fin a → ℂ) × (Fin b → ℂ) with hE
  have hrw : syzygyLocus P H a b = ⋂ i : ℕ, {q : Λ × Metric.sphere (0 : E) 1 |
      (toPoly (q.2 : E).1 * P q.1 + toPoly (q.2 : E).2 * H q.1).coeff i = 0} := by
    ext q
    simp only [syzygyLocus, Set.mem_iInter, Set.mem_ofPred_eq, Polynomial.ext_iff,
      Polynomial.coeff_zero]
  rw [hrw]
  refine isClosed_iInter fun i => ?_
  refine isClosed_eq ?_ continuous_const
  simp only [Polynomial.coeff_add, coeff_toPoly_mul]
  have hval : Continuous fun q : Λ × Metric.sphere (0 : E) 1 => (q.2 : E) :=
    continuous_subtype_val.comp continuous_snd
  refine (continuous_finsetSum _ fun j _ => ?_).add (continuous_finsetSum _ fun j _ => ?_)
  · refine Continuous.mul ((continuous_apply j).comp (continuous_fst.comp hval)) ?_
    by_cases hj : (j : ℕ) ≤ i
    · simp only [if_pos hj]; exact (hPc _).comp continuous_fst
    · simp only [if_neg hj]; exact continuous_const
  · refine Continuous.mul ((continuous_apply j).comp (continuous_snd.comp hval)) ?_
    by_cases hj : (j : ℕ) ≤ i
    · simp only [if_pos hj]; exact (hHc _).comp continuous_fst
    · simp only [if_neg hj]; exact continuous_const

omit [TopologicalSpace Λ] in
/-- **The parameter set is the projection of the syzygy locus.**  This is the Bézout comparison
read as a set identity: a common factor gives a syzygy, which rescales to the sphere without
changing its degree bounds, and a point of the locus gives back a syzygy with those bounds.

Nothing topological enters: only the algebra of the comparison and the rescaling. -/
theorem setOf_hasCommonFactor_eq_image {P H : Λ → ℂ[X]} {n m d : ℕ}
    (hPd : ∀ l, (P l).natDegree = n) (hHd : ∀ l, (H l).natDegree = m)
    (hP0 : ∀ l, P l ≠ 0) (hH0 : ∀ l, H l ≠ 0) (hdm : d ≤ m) :
    {l | HasCommonFactor (P l) (H l) d}
      = Prod.fst '' syzygyLocus P H (m - d + 1) (n - d + 1) := by
  set a := m - d + 1 with ha
  set b := n - d + 1 with hb
  set E := (Fin a → ℂ) × (Fin b → ℂ) with hE
  refine Set.Subset.antisymm (fun l hl => ?_) ?_
  · rw [Set.mem_ofPred_eq, hasCommonFactor_iff (hP0 l) (hH0 l) (by rw [hHd l]; exact hdm)] at hl
    obtain ⟨A, B, hAB, hA, hB, hrel⟩ := hl
    set w : E := (fun i : Fin a => A.coeff (i : ℕ), fun i : Fin b => B.coeff (i : ℕ)) with hw
    have hwA : toPoly w.1 = A := toPoly_coeff A (by rw [hHd l] at hA; omega)
    have hwB : toPoly w.2 = B := toPoly_coeff B (by rw [hPd l] at hB; omega)
    have hw0 : w ≠ 0 := fun h => hAB.elim
      (fun hh => hh (by rw [← hwA]; exact toPoly_eq_zero_iff.mpr (congrArg Prod.fst h)))
      (fun hh => hh (by rw [← hwB]; exact toPoly_eq_zero_iff.mpr (congrArg Prod.snd h)))
    have hsphere : ((‖w‖ : ℂ))⁻¹ • w ∈ Metric.sphere (0 : E) 1 := by
      rw [Metric.mem_sphere, dist_zero_right]; exact norm_smul_inv_norm (𝕜 := ℂ) hw0
    refine ⟨(l, ⟨_, hsphere⟩), ?_, rfl⟩
    change toPoly (((‖w‖ : ℂ)⁻¹ • w : E)).1 * P l + toPoly (((‖w‖ : ℂ)⁻¹ • w : E)).2 * H l = 0
    rw [toPoly_smul_mul_add, hwA, hwB, hrel, mul_zero]
  · rintro _ ⟨q, hq, rfl⟩
    rw [Set.mem_ofPred_eq, hasCommonFactor_iff (hP0 q.1) (hH0 q.1) (by rw [hHd q.1]; exact hdm)]
    have hqne : (q.2 : E) ≠ 0 := ne_zero_of_mem_unit_sphere q.2
    refine ⟨toPoly (q.2 : E).1, toPoly (q.2 : E).2, ?_, ?_, ?_, hq⟩
    · rcases eq_or_ne (q.2 : E).1 0 with h1 | h1
      · exact Or.inr fun h => hqne (Prod.ext h1 (toPoly_eq_zero_iff.mp h))
      · exact Or.inl fun h => h1 (toPoly_eq_zero_iff.mp h)
    · rw [hHd q.1]; have := natDegree_toPoly_le (q.2 : E).1; omega
    · rw [hPd q.1]; have := natDegree_toPoly_le (q.2 : E).2; omega

/-- **The degree of a greatest common divisor is upper semicontinuous.**  For a family of
polynomial pairs of constant degrees whose coefficients vary continuously, the parameters
carrying a common factor of degree at least `d` form a closed set.

The proof is the Bézout comparison plus one compactness: the syzygy `(A,B)` may be normalized to
the unit sphere of the fixed space `K^{m-d+1} × K^{n-d+1}`, and a projection along a compact
factor is a closed map. -/
theorem isClosed_hasCommonFactor {P H : Λ → ℂ[X]} {n m d : ℕ}
    (hPc : ∀ i, Continuous fun l => (P l).coeff i)
    (hHc : ∀ i, Continuous fun l => (H l).coeff i)
    (hPd : ∀ l, (P l).natDegree = n) (hHd : ∀ l, (H l).natDegree = m)
    (hP0 : ∀ l, P l ≠ 0) (hH0 : ∀ l, H l ≠ 0) :
    IsClosed {l | HasCommonFactor (P l) (H l) d} := by
  by_cases hdm : d ≤ m
  swap
  · have : {l | HasCommonFactor (P l) (H l) d} = (∅ : Set Λ) := by
      ext l
      simp only [Set.mem_ofPred_eq, Set.mem_empty_iff_false, iff_false]
      intro h
      exact hdm ((hHd l) ▸ h.le_natDegree (hH0 l))
    rw [this]; exact isClosed_empty
  haveI : CompactSpace
      (Metric.sphere (0 : (Fin (m - d + 1) → ℂ) × (Fin (n - d + 1) → ℂ)) 1) :=
    isCompact_iff_compactSpace.mp (isCompact_sphere _ _)
  rw [setOf_hasCommonFactor_eq_image hPd hHd hP0 hH0 hdm]
  exact isClosedMap_fst_of_compactSpace _ (isClosed_syzygyLocus hPc hHc)

/-- The complementary open set: the parameters at which no common factor of degree `d` occurs. -/
theorem isOpen_not_hasCommonFactor {P H : Λ → ℂ[X]} {n m d : ℕ}
    (hPc : ∀ i, Continuous fun l => (P l).coeff i)
    (hHc : ∀ i, Continuous fun l => (H l).coeff i)
    (hPd : ∀ l, (P l).natDegree = n) (hHd : ∀ l, (H l).natDegree = m)
    (hP0 : ∀ l, P l ≠ 0) (hH0 : ∀ l, H l ≠ 0) :
    IsOpen {l | ¬ HasCommonFactor (P l) (H l) d} :=
  (isClosed_hasCommonFactor hPc hHc hPd hHd hP0 hH0).isOpen_compl

end Topology


/-! ### Axiom footprint -/

/-- info: 'Shields.HasCommonFactor' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms HasCommonFactor

/-- info: 'Shields.syzygyLocus' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms syzygyLocus

end Shields
