/-
Copyright (c) 2026 Johnny Shields. All rights reserved.
Released under the MIT license as described in the file LICENSE.txt.
Authors: Johnny Shields
-/
import Mathlib.Analysis.Complex.Basic
import Mathlib.Analysis.Normed.Module.FiniteDimension
import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.Algebra.Polynomial.Degree.Support
import Mathlib.Algebra.Polynomial.FieldDivision
import Mathlib.Topology.Maps.Proper.Basic

/-!
# Upper semicontinuity of the degree of a greatest common divisor

For a family of pairs of polynomials of constant degrees whose coefficients vary continuously,
the parameters at which the pair carries a common factor of degree at least `d` form a **closed**
set: `deg gcd` cannot jump down in the limit, only up.

The route is the classical Bézout comparison.  Writing `n = deg P` and `m = deg H`,

> `P` and `H` have a common factor of degree `≥ d`
> `⟺ AP + BH = 0` for some `(A,B) ≠ 0` with `deg A ≤ m - d` and `deg B ≤ n - d`,

which turns the condition into the existence of a nonzero vector in a *fixed* finite-dimensional
space, the coefficients of `AP + BH` being polynomial in those of `A`, `B`, `P` and `H`.
Normalizing `(A,B)` to the unit sphere makes the fiber compact, so the parameter set is the image
of a closed set under a projection along a compact factor, hence closed.

## Main definitions

* `Shields.HasCommonFactor`: `P` and `H` admit a common divisor of degree at least `d`.
* `Shields.toPoly`: the polynomial with a prescribed coefficient vector, `∑_{i<a} uᵢXⁱ`.

## Main results

* `Shields.hasCommonFactor_iff`: the Bézout comparison.
* `Shields.isClosed_hasCommonFactor`: **upper semicontinuity**, the closedness statement above.
* `Shields.isOpen_not_hasCommonFactor`: the complementary open set.
* `Shields.eq_empty_of_dense_compl`: an open set with dense complement is empty, so a property
  that is open and holds generically in fact holds everywhere.

## Implementation notes

`HasCommonFactor P H d` is spelled as the existence of a common divisor of degree at least `d`
rather than as `d ≤ (gcd P H).natDegree`, which keeps the statement free of a `DecidableEq`
instance and of any gcd normalization.  The comparison needs no gcd API at all — only that `K[X]`
is a principal ideal ring, so that the ideal generated by `P` and `H` has a generator
`g = uP + vH`, whence `uP₁ + vH₁ = 1` and the divisibility `H₁ ∣ A`.

`toPoly` is an unbundled section of the coefficient map, deliberately not `degreeLTEquiv.symm`:
the argument multiplies it by a varying polynomial and reads off coefficients, and a bare
function into `K[X]` avoids carrying the `degreeLT` subtype through every continuity estimate.

The algebra is over an arbitrary field; only the semicontinuity is stated over `ℂ`, where it uses
that spheres in a finite-dimensional space are compact.

## Tags

polynomial, gcd, resultant, semicontinuity, Bézout, common factor
-/

open Polynomial

namespace Shields

/-! ### Common factors and the Bézout comparison -/

variable {K : Type*} [Field K]

/-- `P` and `H` carry a common factor of degree at least `d`.  This is `d ≤ deg gcd(P,H)`
without naming a gcd, which keeps the statement free of a `DecidableEq` instance. -/
def HasCommonFactor (P H : K[X]) (d : ℕ) : Prop :=
  ∃ g : K[X], g ∣ P ∧ g ∣ H ∧ d ≤ g.natDegree

theorem HasCommonFactor.le_natDegree {P H : K[X]} {d : ℕ} (h : HasCommonFactor P H d)
    (hH : H ≠ 0) : d ≤ H.natDegree :=
  let ⟨_, _, hgH, hdg⟩ := h
  hdg.trans (Polynomial.natDegree_le_of_dvd hgH hH)

theorem hasCommonFactor_zero (P H : K[X]) : HasCommonFactor P H 0 :=
  ⟨1, one_dvd _, one_dvd _, Nat.zero_le _⟩

/-- Bézout in `K[X]`: a common divisor of `P` and `H` that is also a combination of them.  This
is the generator of the ideal they span, and it is all the gcd theory the comparison below
uses. -/
theorem exists_bezout (P H : K[X]) : ∃ g u v : K[X], g ∣ P ∧ g ∣ H ∧ u * P + v * H = g := by
  letI : DecidableEq K := Classical.decEq K
  obtain ⟨u, v, huv⟩ := IsBezout.gcd_eq_sum P H
  exact ⟨IsBezout.gcd P H, u, v, IsBezout.gcd_dvd_left P H, IsBezout.gcd_dvd_right P H, huv⟩

/-- **The Bézout comparison.**  A common factor of degree at least `d` is the same thing as a
nonzero syzygy `AP + BH = 0` with `deg A ≤ deg H - d` and `deg B ≤ deg P - d`.  The forward
direction takes `(A,B) = (H/g, -P/g)`; the backward one divides by the generator of the ideal
spanned by `P` and `H` and reads `H₁ ∣ A` off the Bézout relation. -/
theorem hasCommonFactor_iff {P H : K[X]} (hP : P ≠ 0) (hH : H ≠ 0) {d : ℕ}
    (hd : d ≤ H.natDegree) :
    HasCommonFactor P H d ↔
      ∃ A B : K[X], (A ≠ 0 ∨ B ≠ 0) ∧ A.natDegree ≤ H.natDegree - d ∧
        B.natDegree ≤ P.natDegree - d ∧ A * P + B * H = 0 := by
  constructor
  · rintro ⟨g, ⟨P₁, hP₁⟩, ⟨H₁, hH₁⟩, hdg⟩
    have hg : g ≠ 0 := fun h => hP (by simp [hP₁, h])
    have hP₁0 : P₁ ≠ 0 := fun h => hP (by simp [hP₁, h])
    have hH₁0 : H₁ ≠ 0 := fun h => hH (by simp [hH₁, h])
    have hdegP : P.natDegree = g.natDegree + P₁.natDegree := by
      rw [hP₁, Polynomial.natDegree_mul hg hP₁0]
    have hdegH : H.natDegree = g.natDegree + H₁.natDegree := by
      rw [hH₁, Polynomial.natDegree_mul hg hH₁0]
    refine ⟨H₁, -P₁, Or.inl hH₁0, by omega, ?_, ?_⟩
    · rw [Polynomial.natDegree_neg]; omega
    · rw [hP₁, hH₁]; ring
  · rintro ⟨A, B, hAB, hA, _, hrel⟩
    have hA0 : A ≠ 0 := by
      rcases hAB with h | h
      · exact h
      · intro hA0
        rw [hA0, zero_mul, zero_add] at hrel
        exact h ((mul_eq_zero.mp hrel).resolve_right hH)
    obtain ⟨g, u, v, ⟨P₁, hP₁⟩, ⟨H₁, hH₁⟩, huv⟩ := exists_bezout P H
    have hg : g ≠ 0 := fun h => hP (by simp [hP₁, h])
    have hH₁0 : H₁ ≠ 0 := fun h => hH (by simp [hH₁, h])
    have hone : u * P₁ + v * H₁ = 1 := by
      refine mul_left_cancel₀ hg ?_
      rw [mul_one]
      calc g * (u * P₁ + v * H₁) = u * (g * P₁) + v * (g * H₁) := by ring
        _ = u * P + v * H := by rw [← hP₁, ← hH₁]
        _ = g := huv
    have hcancel : A * P₁ + B * H₁ = 0 := by
      refine mul_left_cancel₀ hg ?_
      rw [mul_zero]
      calc g * (A * P₁ + B * H₁) = A * (g * P₁) + B * (g * H₁) := by ring
        _ = A * P + B * H := by rw [← hP₁, ← hH₁]
        _ = 0 := hrel
    have hdvd : H₁ ∣ A := ⟨v * A - u * B, by
      have : A = A * (u * P₁ + v * H₁) := by rw [hone, mul_one]
      calc A = A * (u * P₁ + v * H₁) := this
        _ = u * (A * P₁ + B * H₁) + H₁ * (v * A - u * B) := by ring
        _ = H₁ * (v * A - u * B) := by rw [hcancel, mul_zero, zero_add]⟩
    have hle : H₁.natDegree ≤ A.natDegree := Polynomial.natDegree_le_of_dvd hdvd hA0
    have hdegH : H.natDegree = g.natDegree + H₁.natDegree := by
      rw [hH₁, Polynomial.natDegree_mul hg hH₁0]
    exact ⟨g, ⟨P₁, hP₁⟩, ⟨H₁, hH₁⟩, by omega⟩

/-! ### Coefficient vectors -/

/-- The polynomial with prescribed coefficient vector, `∑_{i<a} uᵢXⁱ`. -/
noncomputable def toPoly {a : ℕ} (u : Fin a → K) : K[X] := ∑ i : Fin a, C (u i) * X ^ (i : ℕ)

theorem coeff_toPoly {a : ℕ} (u : Fin a → K) (j : ℕ) :
    (toPoly u).coeff j = if h : j < a then u ⟨j, h⟩ else 0 := by
  rw [toPoly, Polynomial.finsetSum_coeff]
  simp only [Polynomial.coeff_C_mul, Polynomial.coeff_X_pow, mul_ite, mul_one, mul_zero]
  by_cases h : j < a
  · rw [dif_pos h]
    rw [Finset.sum_eq_single (⟨j, h⟩ : Fin a)]
    · simp
    · intro c _ hc
      refine if_neg fun hj => hc ?_
      exact Fin.ext hj.symm
    · intro hmem
      exact absurd (Finset.mem_univ _) hmem
  · rw [dif_neg h]
    refine Finset.sum_eq_zero fun i _ => if_neg fun hji => h ?_
    rw [hji]; exact i.isLt

theorem toPoly_eq_zero_iff {a : ℕ} {u : Fin a → K} : toPoly u = 0 ↔ u = 0 := by
  refine ⟨fun h => funext fun i => ?_, fun h => by simp [toPoly, h]⟩
  have hc := coeff_toPoly u (i : ℕ)
  rw [h, Polynomial.coeff_zero, dif_pos i.isLt] at hc
  simpa using hc.symm

theorem natDegree_toPoly_le {a : ℕ} (u : Fin a → K) : (toPoly u).natDegree ≤ a - 1 := by
  rw [Polynomial.natDegree_le_iff_coeff_eq_zero]
  intro j hj
  rw [coeff_toPoly, dif_neg (by omega)]

theorem toPoly_coeff {a : ℕ} (A : K[X]) (h : A.natDegree < a) :
    toPoly (fun i : Fin a => A.coeff (i : ℕ)) = A := by
  ext j
  rw [coeff_toPoly]
  by_cases hj : j < a
  · rw [dif_pos hj]
  · rw [dif_neg hj]
    exact (Polynomial.coeff_eq_zero_of_natDegree_lt (by omega)).symm

theorem toPoly_smul {a : ℕ} (c : K) (u : Fin a → K) : toPoly (c • u) = C c * toPoly u := by
  simp only [toPoly, Finset.mul_sum, Pi.smul_apply, smul_eq_mul, map_mul]
  exact Finset.sum_congr rfl fun i _ => by ring

/-- The coefficients of `(∑_{j<a} uⱼXʲ)P` are the convolution, which is what makes them
continuous in `(u, P)`. -/
theorem coeff_toPoly_mul {a : ℕ} (u : Fin a → K) (P : K[X]) (i : ℕ) :
    (toPoly u * P).coeff i = ∑ j : Fin a, u j * (if (j : ℕ) ≤ i then P.coeff (i - j) else 0) := by
  rw [toPoly, Finset.sum_mul, Polynomial.finsetSum_coeff]
  refine Finset.sum_congr rfl fun j _ => ?_
  have hcomm : C (u j) * X ^ (j : ℕ) * P = C (u j) * (P * X ^ (j : ℕ)) := by ring
  rw [hcomm, Polynomial.coeff_C_mul, Polynomial.coeff_mul_X_pow']

/-! ### Semicontinuity -/

section Topology

variable {Λ : Type*} [TopologicalSpace Λ]

/-- **The degree of a greatest common divisor is upper semicontinuous.**  For a family of
polynomial pairs of constant degrees whose coefficients vary continuously, the parameters
carrying a common factor of degree at least `d` form a closed set.

The proof is the Bézout comparison plus one compactness: the syzygy `(A,B)` may be normalized to
the unit sphere of the fixed space `K^{m-d+1} × K^{n-d+1}`, and a projection along a compact
factor is a closed map. -/
theorem isClosed_hasCommonFactor {P H : Λ → ℂ[X]} {n m d : ℕ}
    (hPc : ∀ i, Continuous fun l => (P l).coeff i)
    (hHc : ∀ i, Continuous fun l => (H l).coeff i)
    (hPd : ∀ l, (P l).natDegree = n) (hHd : ∀ l, (H l).natDegree = m)
    (hP0 : ∀ l, P l ≠ 0) (hH0 : ∀ l, H l ≠ 0) :
    IsClosed {l | HasCommonFactor (P l) (H l) d} := by
  by_cases hdm : d ≤ m
  swap
  · have : {l | HasCommonFactor (P l) (H l) d} = (∅ : Set Λ) := by
      ext l
      simp only [Set.mem_ofPred_eq, Set.mem_empty_iff_false, iff_false]
      intro h
      exact hdm ((hHd l) ▸ h.le_natDegree (hH0 l))
    rw [this]; exact isClosed_empty
  set a := m - d + 1 with ha
  set b := n - d + 1 with hb
  set E := (Fin a → ℂ) × (Fin b → ℂ) with hE
  haveI : CompactSpace (Metric.sphere (0 : E) 1) :=
    isCompact_iff_compactSpace.mp (isCompact_sphere _ _)
  set S : Set (Λ × Metric.sphere (0 : E) 1) :=
    {q | toPoly (q.2 : E).1 * P q.1 + toPoly (q.2 : E).2 * H q.1 = 0} with hS
  have hSclosed : IsClosed S := by
    have hrw : S = ⋂ i : ℕ, {q : Λ × Metric.sphere (0 : E) 1 |
        (toPoly (q.2 : E).1 * P q.1 + toPoly (q.2 : E).2 * H q.1).coeff i = 0} := by
      ext q
      simp only [hS, Set.mem_iInter, Set.mem_ofPred_eq, Polynomial.ext_iff, Polynomial.coeff_zero]
    rw [hrw]
    refine isClosed_iInter fun i => ?_
    refine isClosed_eq ?_ continuous_const
    simp only [Polynomial.coeff_add, coeff_toPoly_mul]
    have hval : Continuous fun q : Λ × Metric.sphere (0 : E) 1 => (q.2 : E) :=
      continuous_subtype_val.comp continuous_snd
    refine (continuous_finsetSum _ fun j _ => ?_).add (continuous_finsetSum _ fun j _ => ?_)
    · refine Continuous.mul ((continuous_apply j).comp (continuous_fst.comp hval)) ?_
      by_cases hj : (j : ℕ) ≤ i
      · simp only [if_pos hj]; exact (hPc _).comp continuous_fst
      · simp only [if_neg hj]; exact continuous_const
    · refine Continuous.mul ((continuous_apply j).comp (continuous_snd.comp hval)) ?_
      by_cases hj : (j : ℕ) ≤ i
      · simp only [if_pos hj]; exact (hHc _).comp continuous_fst
      · simp only [if_neg hj]; exact continuous_const
  have himg : {l | HasCommonFactor (P l) (H l) d} = Prod.fst '' S := by
    ext l
    constructor
    · intro hl
      rw [Set.mem_ofPred_eq, hasCommonFactor_iff (hP0 l) (hH0 l) (by rw [hHd l]; exact hdm)] at hl
      obtain ⟨A, B, hAB, hA, hB, hrel⟩ := hl
      have hAa : A.natDegree < a := by rw [ha, hHd l] at *; omega
      have hBb : B.natDegree < b := by rw [hb, hPd l] at *; omega
      set w : E := (fun i : Fin a => A.coeff (i : ℕ), fun i : Fin b => B.coeff (i : ℕ)) with hw
      have hwA : toPoly w.1 = A := toPoly_coeff A hAa
      have hwB : toPoly w.2 = B := toPoly_coeff B hBb
      have hw0 : w ≠ 0 := by
        intro h
        rcases hAB with hh | hh
        · exact hh (by rw [← hwA, h]; exact toPoly_eq_zero_iff.mpr rfl)
        · exact hh (by rw [← hwB, h]; exact toPoly_eq_zero_iff.mpr rfl)
      have hnorm : ‖w‖ ≠ 0 := fun h => hw0 (norm_eq_zero.mp h)
      set t : ℂ := ((‖w‖ : ℂ))⁻¹ with ht
      have ht0 : t ≠ 0 := inv_ne_zero (by exact_mod_cast hnorm)
      have hsphere : t • w ∈ Metric.sphere (0 : E) 1 := by
        rw [Metric.mem_sphere, dist_zero_right, norm_smul, ht]
        rw [norm_inv, Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg (norm_nonneg w)]
        exact inv_mul_cancel₀ hnorm
      refine ⟨(l, ⟨t • w, hsphere⟩), ?_, rfl⟩
      change toPoly ((t • w : E)).1 * P l + toPoly ((t • w : E)).2 * H l = 0
      have h1 : ((t • w : E)).1 = t • w.1 := rfl
      have h2 : ((t • w : E)).2 = t • w.2 := rfl
      rw [h1, h2, toPoly_smul, toPoly_smul, hwA, hwB]
      calc C t * A * P l + C t * B * H l = C t * (A * P l + B * H l) := by ring
        _ = 0 := by rw [hrel, mul_zero]
    · rintro ⟨q, hq, rfl⟩
      have hqne : (q.2 : E) ≠ 0 := by
        intro h
        have := q.2.2
        rw [Metric.mem_sphere, dist_zero_right, h, norm_zero] at this
        exact zero_ne_one this
      change HasCommonFactor (P q.1) (H q.1) d
      rw [hasCommonFactor_iff (hP0 q.1) (hH0 q.1) (by rw [hHd q.1]; exact hdm)]
      refine ⟨toPoly (q.2 : E).1, toPoly (q.2 : E).2, ?_, ?_, ?_, hq⟩
      · by_cases h1 : (q.2 : E).1 = 0
        · refine Or.inr fun h => ?_
          exact hqne (Prod.ext h1 (toPoly_eq_zero_iff.mp h))
        · exact Or.inl fun h => h1 (toPoly_eq_zero_iff.mp h)
      · have := natDegree_toPoly_le (q.2 : E).1
        rw [hHd q.1]; omega
      · have := natDegree_toPoly_le (q.2 : E).2
        rw [hPd q.1]; omega
  rw [himg]
  exact isClosedMap_fst_of_compactSpace S hSclosed

/-- The complementary open set: the parameters at which no common factor of degree `d` occurs. -/
theorem isOpen_not_hasCommonFactor {P H : Λ → ℂ[X]} {n m d : ℕ}
    (hPc : ∀ i, Continuous fun l => (P l).coeff i)
    (hHc : ∀ i, Continuous fun l => (H l).coeff i)
    (hPd : ∀ l, (P l).natDegree = n) (hHd : ∀ l, (H l).natDegree = m)
    (hP0 : ∀ l, P l ≠ 0) (hH0 : ∀ l, H l ≠ 0) :
    IsOpen {l | ¬ HasCommonFactor (P l) (H l) d} :=
  (isClosed_hasCommonFactor hPc hHc hPd hHd hP0 hH0).isOpen_compl

/-- **An open set with dense complement is empty.**  Consequently a property whose locus is open
and which holds generically holds at *every* point: for such a property "generic" costs nothing,
and no dense open subset ever has to be produced. -/
theorem eq_empty_of_dense_compl {X : Type*} [TopologicalSpace X] {U : Set X} (hU : IsOpen U)
    (hd : Dense Uᶜ) : U = ∅ := by
  rw [← hU.interior_eq, ← compl_compl U, interior_compl, hd.closure_eq, Set.compl_univ]

end Topology

end Shields
